name: Descarregar Set

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL del vídeo de YouTube'
        required: true
      nom:
        description: 'Nom del set (ex: david_guetta_ultra_2016)'
        required: true

jobs:
  descarregar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Instal·lar dependències
        run: |
          pip install yt-dlp google-auth google-auth-oauthlib google-api-python-client
          sudo apt-get install -y ffmpeg
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "
